framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'kane@humblewizards.com'

when@dev:
    framework:
        mailer:
            dsn: 'smtp://127.0.0.1:1025?encryption=null&auth_mode=null'
            message_bus: false

when@test:
    framework:
        mailer:
            dsn: 'null://null'
