name: Deploy to Lightsail

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ vars.SERVER_HOST }}" >> ~/.ssh/known_hosts

      - name: Set release ID
        run: echo "RELEASE=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Create release dir on server
        run: |
          ssh ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }} \
            "mkdir -p ${{ vars.RELEASES_DIR }}/${{ env.RELEASE }}/"
            
      - name: Rsync files to server
        run: |
          rsync -az --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='var' \
            --exclude='.env*' \
            -e "ssh" ./ \
            ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }}:${{ vars.RELEASES_DIR }}/${{ env.RELEASE }}/

      - name: Update symlink and reload
        run: |
          ssh ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }} \
            "ln -sfn ${{ vars.RELEASES_DIR }}/${{ env.RELEASE }} ${{ vars.DEPLOY_PATH }}/current && sudo systemctl reload apache2"
